attributes:
  material_filling:
    api_key: "fw_3ZYLhpzQtRzZKYMpheCBRa6t"
    model: "accounts/fireworks/models/deepseek-r1"
    system_prompt: |
      Extract ONLY the Material Filling attribute from the provided documents.
      
      - Return abbreviations (e.g., GF, GB, MF, T) as a comma-separated list ONLY if additives are explicitly stated to modify the base material’s mechanical properties.
      - Return "none" if the document explicitly states no additives are used in the material.
      
      Output Rules:
      - If additives like GF, GB, MF, or T are directly mentioned, list their abbreviations in the output.
      - If the document confirms no additives are present, return "none".
      - If material filling details are missing, ambiguous, or use non-standard/unclear terms, return "NOT FOUND".
      
      Output format: Material Filling: [abbreviations/none]

  pull_to_seat:
    api_key: "fw_3ZYLhpzQtRzZKYMpheCBRa6t"
    model: "accounts/fireworks/models/deepseek-r1"
    system_prompt: |
      Extract ONLY the Pull-To-Seat attribute from the provided documents.
      
      - Pull-To-Seat refers to terminal/wire insertion requiring a pulling action for final assembly.
      - Return "Yes" ONLY if the connector is explicitly stated to require pull-to-seat action.
      - Return "No" if:
          - The connector uses preassembled retention features to secure terminals without pull-to-seat
          - The document explicitly states pull-to-seat is not used      
      Output format: Pull-To-Seat: [Yes/No]
  
  material_name:
    api_key: "fw_3ZYLhpzQtRzZKYMpheCBRa6t"
    model: "accounts/fireworks/models/deepseek-r1"
    system_prompt: |
      Extract the primary polymer material name from technical documents.
      Rules:
      1. Identify the polymer with the greatest weight fraction
      2. Choose specific grades when available (e.g., PA66 over PA)
      3. Prioritize explicit material declarations
      4. Return single result in uppercase
      5. Return NOT FOUND if unspecified
      
      Valid options: PA, PA66, PBT, PPS, LCP, NOT FOUND
      Output format: Material Name: [value]
      